### PR TITLE
Adding a .yml config file for Code Climate Settings

### PR DESCRIPTION
**Pull request by domducsutcliffe**
So far I have only edited the maintainability settings such that they match the new thresholds in the documentation. For now test coverage are left at default.

### CODE REVIEW

**Comment by domducsutcliffe** [comment]
@tberey Hey Tom could you review this PR? If there's any issues with how I've submited lmk and I can re do it?

**Review by tberey — APPROVED** [review]
Looks Good!

**Comment by domducsutcliffe** [comment]
@tberey do you want to merge it or shall I?

**Comment by tberey** [comment]
@domducsutcliffe you can go ahead an do it, though I've been working on DM today, so you'll need to update the branch with my changes.
You can just press the update branch button to do it. Then merge once that is done, whenever you're ready to

**Comment by tberey** [comment]
@domducsutcliffe Yeah, it was a change I put in earlier, I'll fix it then rerun this for you (and I'll also merge it in for you)

**Comment by tberey** [comment]
Merged in @domducsutcliffe

**Pull request merged**
